
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 30 02:02:54 CST 2013
//----------------------------------------------------

package com.github.lproges.compiler.es;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int BTHAN = 18;
  public static final int CHAR = 11;
  public static final int KW_INT = 2;
  public static final int CASE = 37;
  public static final int PRIVATE = 35;
  public static final int KW_CHAR = 6;
  public static final int INT = 7;
  public static final int INCLUDE_CHAR = 47;
  public static final int FOR = 41;
  public static final int MINUS = 30;
  public static final int BETHAN = 20;
  public static final int CQ = 50;
  public static final int INCLUDE_STRING = 46;
  public static final int NOT = 21;
  public static final int AND = 23;
  public static final int ELSEIF = 43;
  public static final int LTHAN = 17;
  public static final int KW_ARRAY = 49;
  public static final int KW_NORMAL = 44;
  public static final int LP = 26;
  public static final int OR = 22;
  public static final int OQ = 51;
  public static final int DIV = 33;
  public static final int RP = 27;
  public static final int SELECT = 36;
  public static final int EXIT = 38;
  public static final int PLUS = 31;
  public static final int IF = 42;
  public static final int LETHAN = 19;
  public static final int ID = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int LB = 28;
  public static final int EQUAL = 15;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int RB = 29;
  public static final int KW_BOOLEAN = 4;
  public static final int DEQUAL = 16;
  public static final int KW_INCLUDE = 45;
  public static final int PCOMA = 14;
  public static final int KW_OF = 48;
  public static final int PUNTO = 24;
  public static final int WHILE = 40;
  public static final int NEQUAL = 25;
  public static final int DEFAULT = 39;
  public static final int FLOAT = 10;
  public static final int PUBLIC = 34;
  public static final int KW_STRING = 3;
  public static final int MULTI = 32;
  public static final int STRING = 8;
  public static final int KW_FLOAT = 5;
}

